language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - mkdir .reports
  # PHPUnit tests
  - php vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover=.reports/clover.xml

git:
  depth: 1

notifications:
  email:
    - pavelgopanenko@gmail.com
